version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:24.04
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt update
            apt install -y gcc g++ cmake git libsfml-dev xvfb pkg-config
      - run:
          name: Configure project
          command: |
            mkdir -p build
            cd build
            cmake ..
      - run:
          name: Build project
          command: |
            cd build
            make -j$(nproc)
      - run:
          name: Run executable
          command: |
            cd build
            xvfb-run -a ./doodleAP
